name: Run Prettier
on:
  push:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npx prettier --check .
